language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
install: "pip install .[tests]"
script: pytest --cov=point_on_earth
after_success:
  - coveralls
